[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

  # CSP en ENFORCEMENT (ya no Report-Only)
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self';
    connect-src 'self' https://acteco-palet-app.onrender.com wss://acteco-palet-app.onrender.com;
    img-src 'self' https: data: blob:;
    style-src 'self' 'unsafe-inline';
    font-src 'self' data:;
    object-src 'none';
    base-uri 'self';
    frame-ancestors 'none';
    frame-src 'self'
  """

  # Endurecimiento extra (necesitas cámara para html5-qrcode)
  Permissions-Policy = "geolocation=(), camera=(self), microphone=()"
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Resource-Policy = "same-origin"
  X-Permitted-Cross-Domain-Policies = "none"
